### PR TITLE
Addition of bindings for OSAL socket APIs

### PR DESCRIPTION
**Pull request by zec**
This provides safe Rust wrappers for the OSAL socket functions.

In addition, I've added some type parameters to help keep people from, say, trying to send to an IPv6 address when using an IPv4 socket.

### CODE REVIEW

**Comment by dmopalmer** [comment]
From what I read and understood, it looks good.  But has it been tested?  Is it testable before you have the build that can take the OSAL and incorporate it into a test harness?

**Comment by zec** [comment]
It has not been tested, though it will be exercised soon in BlackCAT-internal work, which should uncover any major issues&mdash;the wrapper functions are fairly simple.

In fact, said work did uncover one thing (not directly related to the manually-written wrapper code, though), which I'm about to fix and add to the PR branch.

**Comment by zec** [comment]
...and I realized this morning that just using a default `#[derive(Clone)]` on `Socket` could result in use-after-`close` behavior. [sigh]

Fortunately, that has a relatively simple fix. Fix incoming shortly...

**Review by dmopalmer — APPROVED** [review]
Mostly just bindings.  Needs testing, but since it doesn't interfere with existing functionality, then as long as it doesn't interfere with compilation it will not cause a regression in previous code.

**Pull request merged**
